apiVersion: apps/v1
kind: Deployment
metadata:
  name: productservice
spec:
  selector:
    matchLabels:
      app: productservice
  template:
    metadata:
      labels:
        app: productservice
    spec:
      containers:
      - name: productservice
        image: yschiebelhut/productservice:002
        env:
          - name: DB_USER
            valueFrom:
              configMapKeyRef:
                name: productservice-db-config
                key: MYSQL_USER
          - name: DB_PASS
            valueFrom:
              secretKeyRef:
                name: productservice-db-secret
                key: MYSQL_PASSWORD
          - name: CATEGORY_SERVICE
            value: "categoryservice-service.default.svc.cluster.local/category" # TODO:
          - name: DB_PATH
            value: productservice-db-service.default.svc.cluster.local:3306/productservice # TODO:
        ports:
        - containerPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: productservice-db
spec:
  selector:
    matchLabels:
      app: productservice-db
  template:
    metadata:
      labels:
        app: productservice-db
    spec:
      containers:
      - name: productservice-db
        image: yschiebelhut/productservice-db:002
        env:
          - name: MYSQL_DATABASE
            valueFrom:
              configMapKeyRef:
                name: productservice-db-config
                key: MYSQL_DATABASE
          - name: MYSQL_USER
            valueFrom:
              configMapKeyRef:
                name: productservice-db-config
                key: MYSQL_USER
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: productservice-db-secret
                key: MYSQL_ROOT_PASSWORD
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: productservice-db-secret
                key: MYSQL_PASSWORD
        ports:
        - containerPort: 3306
        volumeMounts:
          - mountPath: /var/lib/mysql
            name: mysql-persistent-storage
      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: productservice-pv-claim

---
apiVersion: v1
kind: Service
metadata:
  name: productservice-service
spec:
  selector:
    app: productservice
  ports:
  - port: 8080
    targetPort: 8080


---
apiVersion: v1
kind: Service
metadata:
  name: productservice-db-service
spec:
  selector:
    app: productservice-db
  ports:
  - port: 3306
    targetPort: 3306
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: categoryservice
spec:
  selector:
    matchLabels:
      app: categoryservice
  template:
    metadata:
      labels:
        app: categoryservice
    spec:
      containers:
      - name: categoryservice
        image: yschiebelhut/categoryservice:002
        env:
          - name: DB_USER
            valueFrom:
              configMapKeyRef:
                name: categoryservice-db-config
                key: MYSQL_USER
          - name: DB_PASS
            valueFrom:
              secretKeyRef:
                name: categoryservice-db-secret
                key: MYSQL_PASSWORD
          - name: PRODUCT_SERVICE
            value: "productservice-service.default.svc.cluster.local/product" # TODO:
          - name: DB_PATH
            value: categoryservice-db-service.default.svc.cluster.local:3306/categoryservice # TODO:
        ports:
        - containerPort: 8080
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: categoryservice-db
spec:
  selector:
    matchLabels:
      app: categoryservice-db
  template:
    metadata:
      labels:
        app: categoryservice-db
    spec:
      containers:
      - name: categoryservice-db
        image: yschiebelhut/categoryservice-db:002
        env:
          - name: MYSQL_DATABASE
            valueFrom:
              configMapKeyRef:
                name: categoryservice-db-config
                key: MYSQL_DATABASE
          - name: MYSQL_USER
            valueFrom:
              configMapKeyRef:
                name: categoryservice-db-config
                key: MYSQL_USER
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: categoryservice-db-secret
                key: MYSQL_ROOT_PASSWORD
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: categoryservice-db-secret
                key: MYSQL_PASSWORD
        ports:
        - containerPort: 3306
        volumeMounts:
          - mountPath: /var/lib/mysql
            name: mysql-persistent-storage
      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: categoryservice-pv-claim

---
apiVersion: v1
kind: Service
metadata:
  name: categoryservice-service
spec:
  selector:
    app: categoryservice
  ports:
  - port: 8080
    targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: categoryservice-db-service
spec:
  selector:
    app: categoryservice-db
  ports:
  - port: 3306
    targetPort: 3306

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: productservice-db-config
data:
  MYSQL_DATABASE: productservice
  MYSQL_USER: productservice
---
apiVersion: v1
kind: Secret
metadata:
  name: productservice-db-secret
data:
  MYSQL_ROOT_PASSWORD: YzhkZTExMGYzNzMwMGE1M2E5NzE3NDkK # c8de110f37300a53a971749
  MYSQL_PASSWORD: MjQwYjJjNmQ1OGZmMmNlMmY1MDhiNDlmCg== # 240b2c6d58ff2ce2f508b49f

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: categoryservice-db-config
data:
  MYSQL_DATABASE: categoryservice
  MYSQL_USER: categoryservice
---
apiVersion: v1
kind: Secret
metadata:
  name: categoryservice-db-secret
data:
  MYSQL_ROOT_PASSWORD: YzhkZTExMGYzNzMwMGE1M2E5NzE3NDkK # c8de110f37300a53a971749
  MYSQL_PASSWORD: MjQwYjJjNmQ1OGZmMmNlMmY1MDhiNDlmCg== # 240b2c6d58ff2ce2f508b49f
