version: "3"
services:
  productservice:
    build: ./productservice/

  productservice-db:
    build: ./productservice/database/

  categoryservice:
    build: ./categoryservice/

  categoryservice-db:
    build: ./categoryservice/database/

