version: "3"
services:
  productservice:
    build: ./productservice/
    networks:
      local_dev_net:
          aliases:
              - productservice

  productservice-db:
    build: ./productservice/database/
    # volumes:
    #   - "./.data/productservice-db:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: c8de110f37300a53a971749
      MYSQL_DATABASE: productservice
      MYSQL_USER: productservice
      MYSQL_PASSWORD: 240b2c6d58ff2ce2f508b49f
    ports:
      - "3306:3306"
    networks:
        local_dev_net:
            aliases:
                - productservice-db

  categoryservice:
    build: ./categoryservice/
    networks:
      local_dev_net:
          aliases:
              - categoryservice
    networks:
      local_dev_net:
          aliases:
              - categoryservice

  categoryservice-db:
    build: ./categoryservice/database/
    # volumes:
    #   - "./.data/categoryservice-db:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: c8de110f37300a53a971749
      MYSQL_DATABASE: categoryservice
      MYSQL_USER: categoryservice
      MYSQL_PASSWORD: 240b2c6d58ff2ce2f508b49f
    ports:
      - "3307:3306"
    networks:
        local_dev_net:
            aliases:
                - categoryservice-db

networks:
  local_dev_net:
    driver: bridge
